name: Deploy to new App Service

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'リソース グループ名'
        required: true
        type: string
      webAppName:
        description: 'Web アプリ名'
        required: true
        type: string
  
env:
  APP_PATH: './src/CS'

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ github.event.inputs.resourceGroup }}
          template: ./templates/app-service.json
          parameters: webAppName=${{ github.event.inputs.webAppName }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Container
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build ${{ env.APP_PATH }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.APP_PATH }} -c Release -o ${{ env.APP_PATH }}/myapp

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ env.APP_PATH }}/myapp
  
  deploy:
    runs-on: ubuntu-latest
    needs: [create, build]

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build jobs
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      
      - name: Deploy to Web app
        id: deploy-to-webAppName
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-${{ github.event.inputs.webAppName }}'
          slot-name: 'Production'
          package: .
      
      - name: logout
        run: |
          az logout
